server:
  port: 84

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: abcdef
    url: jdbc:mysql://101.43.11.65/lottery?useUnicode=true&serverTimezone=Asia/Shanghai


mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml


nacos:
  discovery:
    server-addr: 127.0.0.1:8848

dubbo:
  application:
    name: Lottery
    version: 1.0.0
  #    parameters:
  #      unicast: false
  registry:
    #    address: N/A
    #    address: #multicast://224.5.6.7:1234
    #    address: zookeeper://127.0.0.1:2181
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: cn.itedus.lottery.rpc